In [1]:
import pandas as pd
import numpy as np
import dash_bootstrap_components as dbc
import plotly.express as px
from dash import html
from dash import dcc

In [2]:
data = pd.read_csv(r'US_Accidents_Dec20_new.csv')
data1=data[['ID','Temperature(F)','Wind_Chill(F)','Humidity(%)','Visibility(mi)','Wind_Direction','Wind_Speed(mph)','Precipitation(in)','Civil_Twilight','Nautical_Twilight','Astronomical_Twilight','Weather_Condition']]
data2=data[['City','County','State','Timezone','Start_Lat','Start_Lng','End_Lat','End_Lng']]
data_merged = pd.concat([data1, data2], axis=1)

In [3]:
data_merged

,ID,Temperature(F),Wind_Chill(F),Humidity(%),Visibility(mi),Wind_Direction,Wind_Speed(mph),Precipitation(in),Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,Weather_Condition,City,County,State,Timezone,Start_Lat,Start_Lng,End_Lat,End_Lng
0,A-512230,32.0,23.0,64.0,10.0,W,13.0,0.0,Day,Day,Day,Cloudy,Lockport,Niagara,NY,US/Eastern,43.207451,-78.650032,NaN,NaN
1,A-512231,34.0,27.0,67.0,10.0,W,9.0,0.0,Day,Day,Day,Cloudy,North Tonawanda,Niagara,NY,US/Eastern,43.030651,-78.875862,NaN,NaN
2,A-512232,37.0,30.0,54.0,10.0,W,9.0,0.0,Day,Day,Day,Fair,Silver Creek,Chautauqua,NY,US/Eastern,42.550568,-79.108765,NaN,NaN
3,A-512233,45.0,37.0,80.0,10.0,SW,22.0,0.0,Night,Night,Night,Light Rain / Windy,Boston,Suffolk,MA,US/Eastern,42.362038,-71.071365,NaN,NaN
4,A-512234,45.0,37.0,80.0,10.0,SW,22.0,0.0,Night,Night,Night,Light Rain / Windy,Allston,Suffolk,MA,US/Eastern,42.357281,-71.128036,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1256497,A-3748699,62.0,62.0,26.0,10.0,N,3.0,0.0,Night,Night,Night,Fair,Los Angeles,Los Angeles,CA,US/Pacific,33.929463,-118.254268,33.929463,-118.254268
1256498,A-3748700,50.0,50.0,37.0,10.0,NNE,7.0,0.0,Night,Night,Night,Fair,Winchester,Riverside,CA,US/Pacific,33.696102,-117.084844,33.696102,-117.084844
1256499,A-3748701,59.0,59.0,22.0,10.0,WNW,9.0,NaN,Night,Night,Night,Fair,Mission Hills,Los Angeles,CA,US/Pacific,34.265778,-118.454289,34.265778,-118.454289
1256500,A-3748702,43.0,43.0,86.0,5.0,SSE,3.0,0.0,Night,Night,Night,Fair,Lost Hills,Kern,CA,US/Pacific,35.736667,-119.742500,35.736667,-119.742500
1256501,A-3748703,64.0,64.0,24.0,10.0,NNE,5.0,0.0,Night,Night,Night,Fair,Los Angeles,Los Angeles,CA,US/Pacific,34.075263,-118.281157,34.075263,-118.281157

In [4]:
Top_states=data_merged.groupby(['Weather_Condition', 'State'])["ID"].count()
Top_states_accident=Top_states.reset_index(name='Accident_count')

In [5]:
Top_states_accident.nlargest(10,'Accident_count')

     Weather_Condition State  Accident_count
168               Fair    CA          179511
173               Fair    FL           62044
206               Fair    TX           33698
24              Cloudy    CA           33152
203               Fair    SC           31764
953      Mostly Cloudy    FL           28012
948      Mostly Cloudy    CA           26318
167               Fair    AZ           23181
1076     Partly Cloudy    CA           20512
1081     Partly Cloudy    FL           19255

In [6]:
Top_10_states_accident

NameError: name 'Top_10_states_accident' is not defined

In [7]:
Top_states=data_merged.groupby("State")["ID"].count()

Top_states_accident=Top_states.reset_index(name='Accident_count')
#Taking the top 10
Top_10_states_accident=Top_states_accident.nlargest(10,'Accident_count')

In [9]:
Top_states=data_merged.groupby(['Weather_Condition', 'State'])["ID"].count()
Top_states_accident=Top_states.reset_index(name='Accident_count')

#Taking the top 10
Top_10_states_accident=Top_states_accident.nlargest(10,'Accident_count')

In [10]:
Top_10_states_accident

     Weather_Condition State  Accident_count
168               Fair    CA          179511
173               Fair    FL           62044
206               Fair    TX           33698
24              Cloudy    CA           33152
203               Fair    SC           31764
953      Mostly Cloudy    FL           28012
948      Mostly Cloudy    CA           26318
167               Fair    AZ           23181
1076     Partly Cloudy    CA           20512
1081     Partly Cloudy    FL           19255

In [12]:
data_States = Top_10_states_accident[Top_10_states_accident['Weather_Condition'] == "Fair"]

In [13]:
data_States

    Weather_Condition State  Accident_count
168              Fair    CA          179511
173              Fair    FL           62044
206              Fair    TX           33698
203              Fair    SC           31764
167              Fair    AZ           23181